### ISSUE TITLE
pip指令安装的reqable包仍然是旧版

### ISSUE THREAD

**Issue by psyche314** [reqable/python-scripting-api#2]
pip3 install reqable-scripting
这条指令执行后，安装的python包：
```bash
E:\Projects\Reqable>pip install reqable-scripting
Defaulting to user installation because normal site-packages is not writeable
Collecting reqable-scripting
  Using cached reqable_scripting-1.0.0-py3-none-any.whl.metadata (585 bytes)
Using cached reqable_scripting-1.0.0-py3-none-any.whl (7.4 kB)
Installing collected packages: reqable-scripting
Successfully installed reqable-scripting-1.0.0

E:\Projects\Reqable>python
Python 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import reqable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Breaky\AppData\Roaming\Python\Python312\site-packages\reqable\__init__.py", line 1, in <module>
    import main
ModuleNotFoundError: No module named 'main'
>>>
```

仍然存在不能直接import reqable的问题。
看起来 Pull Request #1 提出的commit尽管被合并到了这个github仓库中，但是没有在pip包中更新。

**Comment by Mymyilmaz** [comment]
> pip3 install reqable-scripting 这条指令执行后，安装的python包： E:\Projects\Reqable>pip install reqable-scripting Defaulting to user installation because normal site-packages is not writeable Collecting reqable-scripting Using cached reqable_scripting-1.0.0-py3-none-any.whl.metadata (585 bytes) Using cached reqable_scripting-1.0.0-py3-none-any.whl (7.4 kB) Installing collected packages: reqable-scripting Successfully installed reqable-scripting-1.0.0
> 
> E:\Projects\Reqable>python Python 3.12.7 (tags/v3.12.7:0b05ead, Oct 1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import reqable
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "C:\Users\Breaky\AppData\Roaming\Python\Python312\site-packages\reqable__init__.py", line 1, in 
> > > > import main
> > > > ModuleNotFoundError: No module named 'main'
> 
> 仍然存在不能直接import reqable的问题。 看起来 Pull Request [#1](https://github.com/reqable/python-scripting-api/pull/1) 提出的commit尽管被合并到了这个github仓库中，但是没有在pip包中更新。

**Comment by Mymyilmaz** [comment]
- [ ] /[](url)
